export type YtDlpErrorCode =
  | 'YTDLP_NOT_INSTALLED'
  | 'YTDLP_EXECUTION_FAILED'
  | 'YTDLP_EXTRACTION_FAILED'
  | 'YTDLP_NETWORK_FAILED'
  | 'YTDLP_JS_RUNTIME_ERROR'
  | 'YTDLP_EXTRACTOR_FAILED'
  | 'UPSTREAM_VIDEO_UNAVAILABLE'
  | 'UPSTREAM_LOGIN_REQUIRED'
  | 'UPSTREAM_REGION_RESTRICTED'
  | 'UPSTREAM_BOT_VERIFICATION_REQUIRED'
  | 'HOSTING_NETWORK_RESTRICTION'
  | 'INVALID_SOURCE_URL'
  | 'MEDIA_NOT_FOUND'
  | 'MEDIA_NOT_AVAILABLE'
  | 'UPSTREAM_AUTH_REQUIRED'
  | 'UPSTREAM_RATE_LIMITED'
  | 'MEDIA_FORMAT_UNAVAILABLE'
  | 'MEDIA_DOWNLOAD_FAILED'
  | 'MEDIA_VALIDATION_FAILED'
  | 'STORAGE_UPLOAD_FAILED'
  | 'TIMEOUT'
  | 'NETWORK_ERROR'
  | 'UNKNOWN_ERROR';

export type JobStatus =
  | 'QUEUED'
  | 'ANALYZING'
  | 'PROCESSING'
  | 'READY'
  | 'FAILED'
  | 'EXPIRED'
  | 'CANCELLED';

export type MediaFormatType = 'video' | 'audio' | 'video_only' | 'audio_only';

export interface MediaFormat {
  id: string;
  format: 'mp4' | 'webm' | 'mp3' | 'm4a' | 'wav' | 'aac';
  quality: string; // e.g. "1080p", "720p", "320 kbps", "128 kbps"
  resolution?: string; // e.g. "1920x1080"
  fps?: number;
  codec?: string;
  hasAudio: boolean;
  hasVideo: boolean;
  fileSizeBytes: number;
  fileSizeFormatted: string;
  directUrl?: string;
  bitrate?: string;
}

export interface MediaMetadata {
  id: string;
  sourceUrl: string;
  sourcePageUrl?: string;
  sourceVideoId?: string;
  provider: string;
  providerIcon?: string;
  title: string;
  description?: string;
  thumbnail: string;
  thumbnailUrl?: string;
  embedUrl?: string;
  youtubeVideoId?: string;
  playableVideoUrl?: string;
  playableVideoMimeType?: string;
  storagePath?: string;
  availableThumbnails?: {
    quality: string;
    width: number;
    height: number;
    url: string;
  }[];
  duration: number; // in seconds
  durationFormatted: string;
  author: {
    name: string;
    url?: string;
    avatar?: string;
  };
  views?: number;
  publishDate?: string;
  formats: MediaFormat[];
  subtitles?: {
    language: string;
    code: string;
    isAutoGenerated: boolean;
    srtUrl?: string;
    vttUrl?: string;
    txtUrl?: string;
  }[];
  isAuthorized: boolean;
  complianceNotice?: string;
}

export interface MediaJob {
  id: string;
  userId?: string;
  sourceUrl: string;
  sourceVideoId?: string;
  provider: string;
  mediaTitle: string;
  thumbnailUrl: string;
  selectedFormat: string;
  selectedQuality: string;
  formatType: 'video' | 'audio' | 'trim' | 'thumbnail' | 'subtitle';
  status: JobStatus;
  progress: number; // 0 to 100
  stepMessage: string;
  resolvedMedia?: {
    id?: string;
    title?: string;
    duration?: number;
    width?: number;
    height?: number;
    codec?: string;
    format?: string;
  };
  downloadToken?: string;
  downloadUrl?: string;
  storageBucket?: string;
  storagePath?: string;
  storageObjectKey?: string;
  fileSizeBytes?: number;
  fileSizeFormatted?: string;
  mimeType?: string;
  sha256?: string;
  errorCode?: YtDlpErrorCode | string;
  errorMessage?: string;
  trimParams?: {
    startTime: number;
    endTime: number;
  };
  createdAt: string;
  updatedAt: string;
  expiresAt: string;
}


export interface UserAccount {
  id: string;
  name: string;
  email: string;
  role: 'user' | 'admin';
  createdAt: string;
  downloadsCount: number;
  tier: 'free' | 'pro';
}

export interface DmcaReport {
  id: string;
  complainantName: string;
  email: string;
  organization?: string;
  targetUrl: string;
  copyrightWorkDescription: string;
  ownershipProofDescription: string;
  reason: string;
  goodFaithStatement: boolean;
  accuracyStatement: boolean;
  status: 'PENDING' | 'UNDER_REVIEW' | 'URL_BLOCKED' | 'REJECTED';
  adminNotes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface ContactMessage {
  id: string;
  name: string;
  email: string;
  subject: string;
  message: string;
  status: 'UNREAD' | 'READ' | 'REPLIED';
  createdAt: string;
}

export interface BlogPost {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  category: string;
  author: string;
  authorAvatar?: string;
  publishedAt: string;
  readTime: string;
  tags: string[];
  featuredImage: string;
  seoTitle: string;
  seoDescription: string;
}

export interface SystemSettings {
  siteName: string;
  maintenanceMode: boolean;
  anonymousRateLimitPerHour: number;
  authenticatedRateLimitPerHour: number;
  maxProcessingDurationSec: number;
  maxFileSizeBytes: number;
  allowTrimming: boolean;
  autoDeleteTemporaryFilesMinutes: number;
  providers: {
    id: string;
    name: string;
    enabled: boolean;
    description: string;
    supportedUrls: string[];
  }[];
}

export interface AuditLog {
  id: string;
  action: string;
  ip: string;
  details: string;
  timestamp: string;
}
