export type AppRoute =
  | '/'
  | '/video-downloader'
  | '/online-video-downloader'
  | '/4k-video-downloader'
  | '/hd-video-downloader'
  | '/video-to-mp3'
  | '/audio-downloader'
  | '/video-converter'
  | '/video-to-mp4'
  | '/video-trimmer'
  | '/thumbnail-downloader'
  | '/subtitle-downloader'
  | '/youtube-downloader'
  | '/youtube-video-downloader'
  | '/youtube-shorts-downloader'
  | '/tiktok-video-downloader'
  | '/instagram-video-downloader'
  | '/x-video-downloader'
  | '/vimeo-video-downloader'
  | '/pinterest-video-downloader'
  | '/bilibili-video-downloader'
  | '/supported-platforms'
  | '/how-it-works'
  | '/faq'
  | '/blog'
  | '/blog/:slug'
  | '/about'
  | '/contact'
  | '/privacy'
  | '/privacy-policy'
  | '/terms'
  | '/copyright'
  | '/dmca'
  | '/security'
  | '/changelog'
  | '/status'
  | '/dashboard'
  | '/admin'
  | '/admin/jobs'
  | '/admin/users'
  | '/admin/reports'
  | '/admin/settings';

export type LanguageCode = 'en' | 'hi' | 'fr' | 'de' | 'es' | 'pt' | 'ja' | 'ko' | 'ar';

export type ThemeMode = 'light' | 'dark' | 'system';

export type AtmosphereScene = 'auto' | 'morning' | 'day' | 'sunset' | 'night' | 'rain' | 'fog';
export type EffectiveScene = 'morning' | 'day' | 'sunset' | 'night' | 'rain' | 'fog';
export type MotionPreference = 'full' | 'reduced' | 'off';

export interface ClientMediaFormat {
  id: string;
  format: 'mp4' | 'webm' | 'mp3' | 'm4a' | 'wav' | 'aac';
  quality: string;
  resolution?: string;
  fps?: number;
  codec?: string;
  hasAudio: boolean;
  hasVideo: boolean;
  fileSizeBytes: number;
  fileSizeFormatted: string;
  directUrl?: string;
  bitrate?: string;
}

export interface ClientMediaMetadata {
  id: string;
  sourceUrl: string;
  sourcePageUrl?: string;
  provider: string;
  title: string;
  description?: string;
  thumbnail: string;
  thumbnailUrl?: string;
  embedUrl?: string;
  youtubeVideoId?: string;
  playableVideoUrl?: string;
  playableVideoMimeType?: string;
  storagePath?: string;
  availableThumbnails?: {
    quality: string;
    width: number;
    height: number;
    url: string;
  }[];
  duration: number;
  durationFormatted: string;
  author: {
    name: string;
    url?: string;
  };
  views?: number;
  publishDate?: string;
  formats: ClientMediaFormat[];
  subtitles?: {
    language: string;
    code: string;
    isAutoGenerated: boolean;
  }[];
  isAuthorized: boolean;
  complianceNotice?: string;
}

export interface ActiveJobState {
  id: string;
  sourceUrl?: string;
  provider?: string;
  status: 'QUEUED' | 'ANALYZING' | 'PROCESSING' | 'READY' | 'FAILED' | 'EXPIRED' | 'CANCELLED';
  progress: number;
  stepMessage: string;
  mediaTitle: string;
  selectedFormat: string;
  selectedQuality: string;
  thumbnailUrl: string;
  downloadUrl?: string;
  playableVideoUrl?: string;
  storagePath?: string;
  downloadToken?: string;
  fileSizeBytes?: number;
  fileSizeFormatted?: string;
  errorCode?: string;
  errorMessage?: string;
}

export interface ToastMessage {
  id: string;
  type: 'success' | 'error' | 'info';
  title: string;
  description?: string;
}
